


print("HenLo would you like a sandwich?")
print("what kind?")
type1 = input("type in sandwich type")
print("thats a bit displeasing,a " + type1 + " sandwich")
print("Hmm, how about we make a sandwich out of scratch")
print("lets choose the ingredients")
print("first, for the bread, we will need a lump of")
type2 = input("type whatever")
print(" that sounds fantastic! Bread made out of" + type2)
print("okay!, now, what kind of cheese, we should get cheese from")
type3 = input ("type where the cheese comes from")
print("yea, a cheese that comes from" + type3 + ",sounds about right!")
print(" okay, now for the MeAt, No VeGans AllOwed")
print(" we should get meat produced from")
type4 = input ("type in location where the meat comes")
print(" yUmmy!, meat from" + type4 + " ,Fantastic!")
print(" now lets choose some toppings!")
print(" every snadwich needs")
type5 = input ("type in a topping")
print("hell yea! every good sandwich needs" + type5)
print("okay, lets choose one more.")
print("what is another topping we should put?")
type6 = input ("type in another topping")
print("oh, thats cool. a sandwich with" + type6)
print("wow, this sadnwich you crated is amazing, lets give it a name!")
type7 = input ("type the name of sandwich")
print("wow! a" + type1 + type2 + type3 + type4 + type5 + type6 +"sandwhich, which is called" + type7)
print("okay! lets send it to your father whos frist and last name is:")
type8 = input ("first name")
type9 = input ("last name")
print("wow so his name is" + type8 + type9)
print("what is his location?")
type10 = input("type in location")
print("nice")


